### ISSUE TITLE
post_copy don't work

### ISSUE THREAD

**Issue by ALDOlivier31** [cea-sec/usbsas#225]
Hi,
If I configure POST_COPY, the client no longer loads. (looping wait animation).

 [post_copy]
 description = "Archive transfer"
 command_bin = "/bin/cp"
 command_args = [
	"%SOURCE_FILE%"
	"/home/olivier/USBSAS/BCKP/"
 ]

Do I need to configure anything else?

**Comment by losynix** [comment]
Hello,

In your example, a comma is missing between the two `command_args`, the program must fail parsing the configuration file.

**Comment by ALDOlivier31** [comment]
OK it works.
Can you correct in the config.toml file as well as in the config.example.toml file?

**Comment by losynix** [comment]
thank you
