### ISSUE TITLE
Cancel/next button positioning

### ISSUE THREAD

**Issue by Olivier-Odace** [cea-sec/usbsas#261]
At the beginning, the first page tells us to insert the Source USB device, 
![20230620_161928](https://github.com/cea-sec/usbsas/assets/50230186/8fd8354b-c4ee-428b-b719-31a8093dee47)

once inserted, this message disappears and it tells us to insert the Destination USB device.
The problem is that this message does not disappear and in French it is (I think) above the buttons which are therefore not clickable.
![20230620_162131](https://github.com/cea-sec/usbsas/assets/50230186/0e581451-8915-4b71-8a5b-dcc18a8deb1d)

Then once the selection of files to transfer has been made, if you are in a directory with several files or sub-directories (side navigation bar present) the "cancel" and "start copying" buttons do not appear or are too low (in French and in English).
![20230620_162322](https://github.com/cea-sec/usbsas/assets/50230186/1ce78c5b-0435-4385-824f-5c8af36cd09d)

To overcome the problem, I go to the system directory of the key which contains only two files and there I can access the buttons.
![20230620_162338](https://github.com/cea-sec/usbsas/assets/50230186/6e54dfde-2009-4683-a50c-82e6646fc03c)

Sorry for my english which is not perfect

**Comment by losynix** [comment]
What is your screen resolution ? I'll admit we mostly tested the UI on relatively big screens. I'll look into this.

**Comment by Olivier-Odace** [comment]
I only have a 10.1" screen with a small resolution of 1024*600 (ideal for a kiosk ;-) )

**Comment by losynix** [comment]
I agree :)

Can you try this branch https://github.com/cea-sec/usbsas/pull/262 ?

**Comment by Olivier-Odace** [comment]
It works!
It's less well arranged but it works...

**Comment by losynix** [comment]
Ok thank you !
