### ISSUE TITLE
Error while transfering files

### ISSUE THREAD

**Issue by Nabil-renault** [cea-sec/usbsas#265]
Hello, when I try to transfer a file to the local storage, the process stops before reaching 100% with the message : “Run error: io error: execution error: Cmd failed”. 

Where does it come from and do you have an idea on how to fix that?

**Comment by Nabil-renault** [comment]
Thanks for the quick answer, yes I'm talking about the Save file on disk option, I did not create manually any /usbsas_data directory (don't know if I had to) I'm locked in the kiosk now and my ssh access isn't working. 
I will try next monday to do a new install and get back to you if I find the /usbsas_data directory or not.

**Comment by Nabil-renault** [comment]
Hello, I have added the /usbsas_data directory that wasn't there, but I still get the same error

**Comment by losynix** [comment]
Does the `usbsas` user have write permission on the directory ?

Can you paste the logs of the transfer ? There should be a line like the following explaining the error:
`[2023-06-27T07:31:39Z ERROR usbsas_cmdexec] cmd stderr: XXXXXXXX`

**Comment by Nabil-renault** [comment]
No it doesn't have write permission on it. Where can I find those logs ? 
I'm using the kiosk version and all I did was to follow the instruction in the kiosk.md file, and I added the usbsas_data directory through a live usb as I do not successfully gain a ssh access to the machine.

**Comment by losynix** [comment]
Ok, I'll add this directory with the correct permission in the package.
You can see the logs by running the command `sudo journalctl -u usbsas-server`

**Comment by Nabil-renault** [comment]
I did a new install and took care of creating a /usbsas_data file (maybe this can be added to the documentation) before installing the deb packages and I no longer have the error. Thank you :)

**Comment by losynix** [comment]
Ok thank you !
I added the directory creation in the debian package, it will be fixed in the next release.
