### ISSUE TITLE
USB to disk no clamv ?

### ISSUE THREAD

**Issue by Etupia** [cea-sec/usbsas#270]
I've been testing the solution for several weeks now, and I've noticed something about clamav's antivirus scanning.
When I perform a USB to USB scan, clamav intervenes before depositing the file(s) on the target USB key.
In the case of a USB to hard disk scan, there is no verification.

I've searched the documentation as well as inspecting the toml configuration files, and I haven't seen anything that explicitly shows how to activate the same functionality that is used with USB to USB.

Is this a deliberate choice on the part of the solution? Is it possible to activate this feature? If so, how? Could this be a bug in the way I've compiled the solution ?

I'd also like to ask if it's possible to have "servers" that only scan and "clients" that send their data to these same servers to validate the status of the files scanned by the clients.
It seems to me that this is possible :

[analyzer]
**url = "http://127.0.0.1:8042/api/scanbundle"**

According to the documentation and in the configuration files, by changing the local IP to private or public 

Thanks in advance for your answers 😀️

**Comment by losynix** [comment]
Hello !

About your first question, you're right, for now file scanning is only done in USB to USB transfers. It was a deliberate choice but we could add this feature to every type of transfers, I'll look into it.

I'm sorry I didn't quite understand your second question. Are you asking about scaning files from a USB device without copying them on a new one ?

**Comment by Etupia** [comment]
Thanks for the answers.

There is a way to enable this functionality easily than I can do into some files ? Or that demand more that ?

For the second question, I was asking if it was possible to have a client (192.168.0.1) and a server with (192.168.0.2) instead to have all in the same for scan.
So the client send their files to 192.168.0.2:8042 (server) instead 127.0.0.1:8042.
If it is not clear, I do schema of what I mean.

**Comment by losynix** [comment]
@Etupia all transfer types can now be analyzed with the remote antivirus. You just need to edit your configuration file, under the `analyzer` section:
```
analyze_usb = true
analyze_net = true
analyze_cmd = true 
```
