### ISSUE TITLE
Setting up network transfert

### ISSUE THREAD

**Issue by Nabil-renault** [cea-sec/usbsas#274]
Hello, what is the config file to set up the network transfer of files, I saw in usbsas-net/src/uploader.rs some reference to http but I would like to know if it is possible to use sftp for the transfer (if yes, I can try to do the modification myself if you tell me where to do them, my first suggestion can be to set up a directory on the machine that is syncronized with the sftp server and use the local transfer to this directory)

**Comment by losynix** [comment]
Hello,

Indeed, the built-in uploader only supports HTTP. However you can use the _command_ destination to upload files with SFTP.
In the example configuration file, the _command_ destination calls the `cp`  program to save the files in the local disk:

```
[command]
description = "Save files on disk"
longdescr = "Save out tar in /usbsas_data/"
command_bin = "/bin/cp"
command_args = [
    "%SOURCE_FILE%",
    "/usbsas_data/"
]
```

You can change the configuration file to call your own program or script to do whatever you want with the files from the transfer.

N.B.: Files transferred using the `command` or `network` destination are not analyzed by the antivirus for now (but this will be fixed soon)

**Comment by Nabil-renault** [comment]
Hello, thanks for the answer. I did try to do that with the execution of a script of mine but it doesn't work. I do not know why, and to know why I guess that will have to check with systemctl but I can't as my ssh connection do not work anymore after the installation of usbsas (worked right before the reboot at the end). Any clue about that ? (I can use a live boot to get more information)

**Comment by losynix** [comment]
I have no idea sorry, usbsas packages don't alter network or firewall configuration

**Comment by Nabil-renault** [comment]
Hello, sounds like the network issue is fixed on my side, but when I try to use my custom command that upload the file on a sftp server instead of saving it on the machine I get a `run error: io error: execution error: Failed to start child cmd` but my command that call  works with ssh and and I gave to all the user the execution rights on my srcipt. Here's what I changed in the config file : `command_bin = "/home/debian/testsftp.sh"
command_args = [
    "%SOURCE_FILE%"
]`

**Comment by Nabil-renault** [comment]
I cannot do a `su usbsas` while connected with ssh, it says "This account is currently not available", I even tried before the final step of the install and it was the same.

Is it possible to update the machine instead of installing it again from scratch ? I mean to get a newer version and/or to apply the modifications of the config file ?

**Comment by losynix** [comment]
> I cannot do a `su usbsas`

`usbsas` is a system account, you can't login with it. You could try running your script as the `usbsas` user like this: `sudo -u usbsas /home/debian/testsftp.sh`. Make your this script is readable and executable by `usbsas`.

> Is it possible to update the machine instead of installing it again from scratch ?

Yes, you only need to update / re-intsall the usbsas packages.

**Comment by Nabil-renault** [comment]
Ok thanks, it was a permission issue.
